schema-version: 1.0


var:
  version: 1.15.3

provision:
  - pkg: git
  - url:
      from: https://golang.org/dl/go{% version %}.linux-amd64.tar.gz
      to: /usr/local
  - systempath:
      paths:
        - /usr/local/go/bin
        - /root/go/bin
  - shell: go get github.com/go-delve/delve/cmd/dlv
